# Mock classifier

ARG BASE_VERSION=0.16.6

FROM arxiv/base:${BASE_VERSION}

WORKDIR /opt/arxiv/

# Add Python consumer and configuration.
RUN pip install -U pip pipenv uwsgi && pipenv install flask uwsgi --skip-lock && rm -rf ~/.cache/pip
RUN pipenv install flask uwsgi

ADD mock-services/mock_classifier.py /opt/arxiv/

ENTRYPOINT ["pipenv", "run"]
CMD ["uwsgi", "--http-socket", ":8000", "-M", "-t", "3000", "--manage-script-name", "--processes", "8", "--threads", "1", "--mount", "/=mock_classifier.py"]
